blank_issues_enabled: true
contact_links:
  - name: Burr Open Source Discord Server
    url: https://discord.gg/SEjkgvYHRb
    about: We are piloting using discrod for chat. Feel free to try asking questions there first.
