name: Node.js CI

on:
  push:
    branches:
      - main
    paths:
      - 'telemetry/ui/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'telemetry/ui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: telemetry/ui
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npm run build
    - run: npm run lint:fix
    - run: npm run format:fix
